import "./globals.css";
import CustomNavbar from "./components/Navbar/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata = {
  title: "Quick - Stay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <CustomNavbar/>
        {children}
      </body>
    </html>
  );
}
